# Generated by Django 6.0.3 on 2026-03-14 18:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_is_featured_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("sku", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "max_quantity_per_order",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "price", "id"],
            },
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="products_ca_name_693421_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="products_ca_slug_da4386_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="products_ca_is_acti_a2d000_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_title_7d8124_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_slug_3edc0c_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_price_9b1a5f_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_is_acti_ca4d9a_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_created_52f0d7_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_is_feat_a5d7cd_idx",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="max_quantity_per_order",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "name")},
        ),
    ]
