# Generated by Django 6.0.3 on 2026-04-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productvariant_price_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="products_ca_name_693421_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="products_ca_slug_da4386_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="products_ca_is_acti_a2d000_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_title_7d8124_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_slug_3edc0c_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_categor_9edb3d_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_is_acti_ca4d9a_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_is_feat_a5d7cd_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_is_feat_a1ecf6_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="products_pr_product_cee51f_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="products_pr_sku_dcab68_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="products_pr_price_a59bc5_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="products_pr_stock_q_989677_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="products_pr_is_acti_9d6315_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="products_pr_product_3a28fe_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="products_pr_product_134faf_idx",
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variants",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["tenant", "name"], name="products_ca_tenant__2cf0be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["tenant", "slug"], name="products_ca_tenant__70e641_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["tenant", "is_active"], name="products_ca_tenant__e78933_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant", "title"], name="products_pr_tenant__2e9e53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant", "slug"], name="products_pr_tenant__24ea68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant", "category"], name="products_pr_tenant__a8981a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant", "is_active"], name="products_pr_tenant__7042ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant", "is_featured", "is_active"],
                name="products_pr_tenant__dca2b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["tenant", "product"], name="products_pr_tenant__7a0c8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["tenant", "sku"], name="products_pr_tenant__dedc6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["tenant", "price"], name="products_pr_tenant__485de7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["tenant", "stock_quantity"],
                name="products_pr_tenant__f1a41e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["tenant", "is_active"], name="products_pr_tenant__bb99f5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_category_name_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="unique_category_slug_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("tenant", "title"), name="unique_product_title_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="unique_product_slug_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="unique_variant_name_per_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sku"), name="unique_variant_sku_per_tenant"
            ),
        ),
    ]
