# Generated by Django 4.2.15 on 2026-05-06 21:08

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("products", "0005_remove_category_products_ca_name_693421_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_urls",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="category_image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="hero_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="product_hero_image"
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="product_gallery_image"
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "product"],
                        name="products_pr_tenant__0f264d_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="products_pr_tenant__b1c1b6_idx",
                    ),
                    models.Index(
                        fields=["product", "is_active"],
                        name="products_pr_product_53526a_idx",
                    ),
                    models.Index(
                        fields=["product", "sort_order"],
                        name="products_pr_product_f88290_idx",
                    ),
                ],
            },
        ),
    ]
