# Generated by Django 6.0.3 on 2026-03-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_orderitem_unique_product_per_order_and_more"),
        ("products", "0004_alter_productvariant_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_title",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_name",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_sku",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "variant"], name="orders_orde_order_i_c8de3b_idx"
            ),
        ),
    ]
