# Generated by Django 6.0.3 on 2026-03-18 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "addresses",
            "0003_remove_customeraddress_addresses_c_created_4c4c08_idx_and_more",
        ),
        ("orders", "0004_alter_orderitem_product_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="addresses.customeraddress",
            ),
            preserve_default=False,
        ),
    ]
