# Generated by Django 6.0.3 on 2026-03-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_image",
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
