# Generated by Django 6.0.3 on 2026-04-11 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "addresses",
            "0003_remove_customeraddress_addresses_c_created_4c4c08_idx_and_more",
        ),
        ("orders", "0006_orderitem_product_image"),
        ("products", "0005_remove_category_products_ca_name_693421_idx_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("AWAITING_PAYMENT", "Awaiting payment"),
                            ("PROCESSING", "Processing"),
                            ("PAID", "Paid"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("AWAITING_PAYMENT", "Awaiting payment"),
                            ("PROCESSING", "Processing"),
                            ("PAID", "Paid"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_slug_08ef1e_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_status_c6dd84_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orders_orde_order_i_5d347b_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orders_orde_product_32ff41_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orders_orde_variant_164791_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orders_orde_order_i_c8de3b_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("AWAITING_PAYMENT", "Awaiting payment"),
                    ("PROCESSING", "Processing"),
                    ("PAID", "Paid"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "slug"], name="orders_orde_tenant__a7b88b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "status"], name="orders_orde_tenant__291115_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["tenant", "order"], name="orders_orde_tenant__1e7123_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["tenant", "product"], name="orders_orde_tenant__93c3cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["tenant", "variant"], name="orders_orde_tenant__45cae0_idx"
            ),
        ),
        migrations.AddField(
            model_name="orderstatusevent",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_status_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderstatusevent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_events",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderstatusevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_status_events",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatusevent",
            index=models.Index(
                fields=["tenant", "order"], name="orders_orde_tenant__8ee77f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatusevent",
            index=models.Index(
                fields=["tenant", "to_status"], name="orders_orde_tenant__42e9cf_idx"
            ),
        ),
    ]
