# Generated by Django 6.0.3 on 2026-04-23 16:50

import inspect
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


_CHECK_CONSTRAINT_USES_CONDITION = (
    "condition" in inspect.signature(models.CheckConstraint).parameters
)


def build_check_constraint(*, predicate, name):
    kwargs = {"name": name}
    kwargs["condition" if _CHECK_CONSTRAINT_USES_CONDITION else "check"] = predicate
    return models.CheckConstraint(**kwargs)


class Migration(migrations.Migration):

    dependencies = [
        (
            "addresses",
            "0003_remove_customeraddress_addresses_c_created_4c4c08_idx_and_more",
        ),
        ("orders", "0007_orderstatusevent_alter_order_options_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_additional_information",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="address_region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kampala_area", "Kampala Area"),
                    ("entebbe_area", "Entebbe Area"),
                    ("central_region", "Central Region"),
                    ("eastern_region", "Eastern Region"),
                    ("northern_region", "Northern Region"),
                    ("western_region", "Western Region"),
                    ("rest_of_kampala", "Rest of Kampala"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="address_street_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="addresses.customeraddress",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["guest_session_key", "status"],
                name="orders_orde_guest_s_394eee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_email"], name="orders_orde_custome_ca0107_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=build_check_constraint(
                predicate=models.Q(
                    ("user__isnull", False),
                    ("guest_session_key__isnull", False),
                    _connector="OR",
                ),
                name="order_requires_user_or_guest_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=build_check_constraint(
                predicate=models.Q(
                    ("user__isnull", False),
                    ("guest_session_key__isnull", False),
                    _negated=True,
                ),
                name="order_owner_is_exclusive",
            ),
        ),
    ]
