# Generated by Django 6.0.3 on 2026-04-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_pickupstation"),
        ("orders", "0008_order_address_additional_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                choices=[
                    ("HOME_DELIVERY", "Home delivery"),
                    ("PICKUP_STATION", "Pickup station"),
                ],
                db_index=True,
                default="HOME_DELIVERY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="shipping.pickupstation",
            ),
        ),
    ]
