# Generated by Django 6.0.3 on 2026-04-23 16:50

import inspect
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


_CHECK_CONSTRAINT_USES_CONDITION = (
    "condition" in inspect.signature(models.CheckConstraint).parameters
)


def build_check_constraint(*, predicate, name):
    kwargs = {"name": name}
    kwargs["condition" if _CHECK_CONSTRAINT_USES_CONDITION else "check"] = predicate
    return models.CheckConstraint(**kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_cartitem_unique_product_per_cart_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="guest_session_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=40, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=build_check_constraint(
                predicate=models.Q(
                    ("user__isnull", False),
                    ("guest_session_key__isnull", False),
                    _connector="OR",
                ),
                name="cart_requires_user_or_guest_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=build_check_constraint(
                predicate=models.Q(
                    ("user__isnull", False),
                    ("guest_session_key__isnull", False),
                    _negated=True,
                ),
                name="cart_owner_is_exclusive",
            ),
        ),
    ]
