# Generated by Django 6.0.3 on 2026-03-06 21:23

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customeraddress",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
            },
        ),
        migrations.RemoveField(
            model_name="customeraddress",
            name="slug",
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="address_line2",
            field=models.CharField(
                blank=True, default=django.utils.timezone.now, max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["created_at"], name="addresses_c_created_4c4c08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["is_default"], name="addresses_c_is_defa_570f0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(fields=["city"], name="addresses_c_city_0ca99b_idx"),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["country"], name="addresses_c_country_2d2c4a_idx"
            ),
        ),
    ]
