# Generated by Django 6.0.3 on 2026-03-18 17:49

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customeraddress",
            name="addresses_c_created_4c4c08_idx",
        ),
        migrations.RemoveIndex(
            model_name="customeraddress",
            name="addresses_c_is_defa_570f0d_idx",
        ),
        migrations.RemoveIndex(
            model_name="customeraddress",
            name="addresses_c_city_0ca99b_idx",
        ),
        migrations.RemoveIndex(
            model_name="customeraddress",
            name="addresses_c_country_2d2c4a_idx",
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="additional_information",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="additional_telephone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="region",
            field=models.CharField(
                choices=[
                    ("kampala_area", "Kampala Area"),
                    ("entebbe_area", "Entebbe Area"),
                    ("central_region", "Central Region"),
                    ("eastern_region", "Eastern Region"),
                    ("northern_region", "Northern Region"),
                    ("western_region", "Western Region"),
                    ("rest_of_kampala", "Rest of Kampala"),
                ],
                db_index=True,
                default="kampala_area",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="street_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Street Name / Building Number / Apartment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="is_default",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["user", "-is_default", "-created_at"],
                name="addresses_c_user_id_731f88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["user", "city"], name="addresses_c_user_id_34b1a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["user", "region"], name="addresses_c_user_id_2c56b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customeraddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="unique_default_address_per_user",
            ),
        ),
        migrations.RemoveField(
            model_name="customeraddress",
            name="address_line1",
        ),
        migrations.RemoveField(
            model_name="customeraddress",
            name="address_line2",
        ),
        migrations.RemoveField(
            model_name="customeraddress",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customeraddress",
            name="label",
        ),
        migrations.RemoveField(
            model_name="customeraddress",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="customeraddress",
            name="state",
        ),
    ]
