# Generated by Django 6.0.3 on 2026-04-11 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(default="UGX", max_length=10)),
                (
                    "default_country",
                    models.CharField(blank=True, default="Uganda", max_length=100),
                ),
                ("timezone", models.CharField(default="Africa/Kampala", max_length=64)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["slug", "is_active"], name="tenants_ten_slug_7c647c_idx"
                    ),
                    models.Index(
                        fields=["is_default", "is_active"],
                        name="tenants_ten_is_defa_be204d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_name", models.CharField(blank=True, max_length=255)),
                ("logo_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(blank=True, max_length=20)),
                ("secondary_color", models.CharField(blank=True, max_length=20)),
                ("accent_color", models.CharField(blank=True, max_length=20)),
                ("splash_image_url", models.URLField(blank=True)),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("hero_subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant branding",
                "verbose_name_plural": "Tenant branding",
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_notifications_enabled", models.BooleanField(default=True)),
                ("reviews_enabled", models.BooleanField(default=True)),
                ("coupons_enabled", models.BooleanField(default=True)),
                ("delivery_enabled", models.BooleanField(default=True)),
                ("wishlist_enabled", models.BooleanField(default=True)),
                ("support_chat_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("terms_url", models.URLField(blank=True)),
                ("privacy_url", models.URLField(blank=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant settings",
                "verbose_name_plural": "Tenant settings",
            },
        ),
        migrations.CreateModel(
            name="TenantFeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=100)),
                ("enabled", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "enabled"],
                        name="tenants_ten_tenant__89b7dd_idx",
                    )
                ],
                "unique_together": {("tenant", "key")},
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super admin"),
                            ("tenant_owner", "Tenant owner"),
                            ("tenant_admin", "Tenant admin"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "role", "is_active"],
                        name="tenants_ten_tenant__f04c06_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="tenants_ten_user_id_8b073c_idx",
                    ),
                ],
                "unique_together": {("tenant", "user")},
            },
        ),
    ]
