# Generated by Django 6.0.3 on 2026-04-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_category_products_ca_name_693421_idx_and_more"),
        ("promotions", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["tenant", "code"], name="promotions__tenant__f7a099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["tenant", "is_active"], name="promotions__tenant__6ba11b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_coupon_code_per_tenant"
            ),
        ),
    ]
