# Generated by Django 6.0.3 on 2026-03-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("UGX", "Ugandan Shilling"), ("EUR", "Euro")],
                default="UGX",
                max_length=10,
            ),
        ),
    ]
