# Generated by Django 6.0.3 on 2026-04-11 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_orderstatusevent_alter_order_options_and_more"),
        ("payments", "0005_alter_payment_currency"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_referen_75358f_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_status_7ad4af_idx",
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "reference"], name="payments_pa_tenant__71b5da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "status"], name="payments_pa_tenant__3ffcb1_idx"
            ),
        ),
    ]
