# Generated by Django 4.2.15 on 2026-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_payment_guest_session_key_alter_payment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Bank / Debit Card"),
                    ("STRIPE", "Stripe"),
                    ("PAYSTACK", "Paystack"),
                    ("FLUTTERWAVE", "Flutterwave"),
                    ("MTN", "MTN Mobile Money"),
                ],
                max_length=20,
            ),
        ),
    ]
