# Generated by Django 6.0.3 on 2026-04-14 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_newslettersubscriber"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="confirmation_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="newslettersubscriber",
            constraint=models.UniqueConstraint(
                fields=("email", "tenant"),
                name="unique_newsletter_subscriber_per_tenant",
            ),
        ),
    ]
