# Generated by Django 6.0.3 on 2026-03-28 15:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_emailotp_customuser_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="default.jpg",
                max_length=255,
                null=True,
                verbose_name="avatar",
            ),
        ),
    ]
