# Generated by Django 6.0.3 on 2026-04-24 12:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("opening_hours", models.CharField(blank=True, max_length=255)),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_stations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["city", "area", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="pickupstation",
            index=models.Index(
                fields=["tenant", "city", "area"],
                name="shipping_pi_tenant__6c2975_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pickupstation",
            index=models.Index(
                fields=["tenant", "is_active"],
                name="shipping_pi_tenant__f4c626_idx",
            ),
        ),
    ]
