# Generated by Django 6.0.3 on 2026-04-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_pickupstation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pickupstation",
            new_name="shipping_pi_tenant__16599c_idx",
            old_name="shipping_pi_tenant__6c2975_idx",
        ),
        migrations.RenameIndex(
            model_name="pickupstation",
            new_name="shipping_pi_tenant__7c2155_idx",
            old_name="shipping_pi_tenant__f4c626_idx",
        ),
        migrations.AlterField(
            model_name="pickupstation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
