# Generated by Django 6.0.3 on 2026-03-16 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productvariant_price_and_more"),
        ("reviews", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "created_at"], name="reviews_rev_product_847b15_idx"
            ),
        ),
    ]
