# Generated by Django 6.0.3 on 2026-03-17 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productvariant_price_and_more"),
        ("reviews", "0003_review_reviews_rev_product_847b15_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "product"], name="reviews_rev_user_id_eefe96_idx"
            ),
        ),
    ]
