# Generated by Django 6.0.3 on 2026-04-01 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_devicetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="app_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="device_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="last_seen_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "is_active"], name="notificatio_user_id_f0e72c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["platform", "is_active"], name="notificatio_platfor_786102_idx"
            ),
        ),
    ]
