# Generated by Django 6.0.3 on 2026-04-11 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0004_devicetoken_app_version_devicetoken_device_id_and_more",
        ),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="devicetoken",
            name="notificatio_user_id_f0e72c_idx",
        ),
        migrations.RemoveIndex(
            model_name="devicetoken",
            name="notificatio_platfor_786102_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_is_read_9edb86_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_created_46ad24_idx",
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_tokens",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["tenant", "user", "is_active"],
                name="notificatio_tenant__7af6bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["tenant", "platform", "is_active"],
                name="notificatio_tenant__10316d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "is_read"], name="notificatio_tenant__67b689_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "created_at"], name="notificatio_tenant__b302ab_idx"
            ),
        ),
    ]
